### PR TITLE
Adds ability to configure whether resource keys should case sensitive in Localization

### PR DESCRIPTION
**Pull request by jimmyrn**
… in Localization

### CODE REVIEW

**Comment by burningice2866** [comment]
Doesn't actually do anything or is it up to the consumer to act on the configuration?

**Comment by jimmyrn** [comment]
No, you should configure this in the consumer web.config file like you're configuring eCommerce. For example:
```
<configSections>
    <sectionGroup name="compositeC1Contrib">
      <section name="localization" type="CompositeC1Contrib.Localization.Configuration.LocalizationSection, CompositeC1Contrib.Localization" />
    </sectionGroup>
</configSections>

<compositeC1Contrib>
    <localization ignoreCase="true" />
</compositeC1Contrib>
```

**Comment by burningice2866** [comment]
Ah, i hadn't noticed its setting a property which already exists on the .Net ResourceManager class.

https://github.com/burningice2866/CompositeC1Contrib/pull/2/commits/fe7ad8bc35ae50875d739de499d2fb2781610140#diff-efdf00e3dae036c0d691d82fd9b80e8fR28

**Comment by burningice2866** [comment]
Why would you ever need this? Even the official documentation (https://msdn.microsoft.com/en-us/library/system.resources.resourcemanager.ignorecase(v=vs.110).aspx) states that

**_For performance reasons, it is best to always specify the correct case for your resource names. Setting IgnoreCase to true can cause a significant increase in working set and a significant decline in performance._**

**Comment by jimmyrn** [comment]
Well, in a repo with hundreds of key-strings with inconsitent casing, this is handy.

**Comment by burningice2866** [comment]
Allright.. as long as the default setting is false, as it is, i'm fine with it. Just strip this latest commit and i'll merge it in https://github.com/burningice2866/CompositeC1Contrib/pull/2/commits/4c717b40f2174211d928de458d93d44c8a9cfd7e

**Pull request merged**
